name: DAST - ZAP Baseline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for app
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:3000 >/dev/null; then
              echo "App is up"; exit 0
            fi
            sleep 2
          done
          echo "App did not start in time"; exit 1

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:3000'
          fail_action: false
          cmd_options: '-a -j'
          zap_home: /tmp
        # -a: include alpha rules; -j: JSON output as well

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: |
            report_html.html
            *.json
            zap*.log
          if-no-files-found: warn
